#pragma once
/* This file has been generated by VisualGDB.
   DO NOT EDIT MANUALLY. THE FILE WILL BE OVERWRITTEN.
   Use VisualGDB Project Properties window to edit these settings instead. */

#pragma once
#include <stdint.h>
#include "bsp_api.h"
#include "r_ioport.h"
#include "bsp_pin_cfg.h"

FSP_HEADER
/* IOPORT Instance */
extern const ioport_instance_t g_ioport;

/* IOPORT control structure. */
extern ioport_instance_ctrl_t g_ioport_ctrl;

void g_common_init(void);
FSP_FOOTER
