#pragma once
/* This file has been generated by VisualGDB.
   DO NOT EDIT MANUALLY. THE FILE WILL BE OVERWRITTEN.
   Use VisualGDB Project Properties window to edit these settings instead. */

#pragma once
#include <stdint.h>
#include "bsp_api.h"
#include "common_data.h"
FSP_HEADER
void hal_entry(void);
void g_hal_init(void);
FSP_FOOTER
