/* This file has been generated by VisualGDB.
   DO NOT EDIT MANUALLY. THE FILE WILL BE OVERWRITTEN.
   Use VisualGDB Project Properties window to edit these settings instead. */

#include "hal_data.h"
void g_hal_init(void)
{
    g_common_init ();
}
