#pragma once
/* This file has been generated by VisualGDB.
   DO NOT EDIT MANUALLY. THE FILE WILL BE OVERWRITTEN.
   Use VisualGDB Project Properties window to edit these settings instead. */

#define BSP_MCU_R7FA2E1A92DFM
#define BSP_ROM_SIZE_BYTES (131072)
#define BSP_RAM_SIZE_BYTES (16384)
#define BSP_DATA_FLASH_SIZE_BYTES (4096)
#define BSP_PACKAGE_LQFP
#define BSP_PACKAGE_PINS (64)

